# Generated by Django 4.2.7 on 2026-04-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('reason', models.CharField(choices=[('post_created', 'Создал пост'), ('helpful_answer', 'Помог другому студенту'), ('activity', 'Активность'), ('comment', 'Оставил комментарий'), ('story_posted', 'Выложил историю'), ('club_participation', 'Участие в клубе'), ('admin_bonus', 'Бонус от администрации')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
