# Generated by Django 4.2.7 on 2026-04-02 03:21

import apps.stories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='stories/')),
                ('media_type', models.CharField(choices=[('image', 'Фото'), ('video', 'Видео')], max_length=10)),
                ('text_overlay', models.CharField(blank=True, max_length=200)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(default=apps.stories.models.story_expires)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'ordering': ['-created_at'],
            },
        ),
    ]
