# Generated by Django 4.2.7 on 2026-04-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('announcement', 'Объявление'), ('event', 'Событие'), ('achievement', 'Достижение'), ('scholarship', 'Стипендия'), ('general', 'Общее')], default='general', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
